### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by idontknowwhateverr** [DSJAS/DSJAS#88]
When i verify the setup code, it hangs for a bit and then shows this
Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: ���� ���� ����������. in C:\xampp\htdocs\include\install\Database.php on line 129

Warning: mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: ���� ���� ����������. in C:\xampp\htdocs\include\install\Database.php on line 129

Fatal error: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, bool given in C:\xampp\htdocs\include\install\Database.php:64 Stack trace: #0 C:\xampp\htdocs\include\install\Database.php(64): mysqli_query(false, 'SELECT * FROM `...') #1 C:\xampp\htdocs\include\install\Database.php(17): tableExists('users') #2 C:\xampp\htdocs\admin\install\db_config.php(32): databaseInstalled() #3 {main} thrown in C:\xampp\htdocs\include\install\Database.php on line 64

![image](https://github.com/DSJAS/DSJAS/assets/173405532/16448a79-db4a-4d2a-80d9-71598a09d671)

**Comment by ejv2** [comment]
Hello! Would you mind please posting the contents of your Config.ini file? Make sure you censor the database password (probably not important but can't be too safe).

This error seems to mean that DSJAS tried to connect to the database server and couldn't because of a bad hostname.

**Comment by ejv2** [comment]
Any progress on this?
