### ISSUE TITLE
Error - Failed: No such host is known. 

### ISSUE THREAD

**Issue by ChuckinAllen** [DSJAS/DSJAS#90]
After adding token, I am getting theses errors, not entirely sure how to fix them.

Success You have successfully authenticated as the owner of the website and can now continue the setup process.

Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known. in C:\xampp\htdocs\include\install\Database.php on line 129

Warning: mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: No such host is known. in C:\xampp\htdocs\include\install\Database.php on line 129

Fatal error: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, bool given in C:\xampp\htdocs\include\install\Database.php:64 Stack trace: #0 C:\xampp\htdocs\include\install\Database.php(64): mysqli_query(false, 'SELECT * FROM `...') #1 C:\xampp\htdocs\include\install\Database.php(17): tableExists('users') #2 C:\xampp\htdocs\admin\install\db_config.php(32): databaseInstalled() #3 {main} thrown in C:\xampp\htdocs\include\install\Database.php on line 64

**Comment by ejv2** [comment]
Do you have a valid config file?

**Comment by ChuckinAllen** [comment]
Config.ini 

[setup]
install_finalized="0"
installed="1"
owner_verified="1"
database_installed="0"
[database]
running_without_database="0"
server_hostname="database"
database_name="dsjas"
username="DSJAS"
password="DSJAS-Default-Password-1234"
[customization]
bank_name="Dave Smith Johnson and Son"
bank_domain="dsjas.financial"
[settings]
disable_admin="0"
simulate_missing_nolog_admin="0"

**Comment by ejv2** [comment]
This is a bug which I believe I have now fixed. Are you using a release or did you pull from git?

**Comment by ejv2** [comment]
In case you are debugging this later on, the actual bug is on the fatal error line. The above warnings are expected on a fresh install.

**Comment by ChuckinAllen** [comment]
I am using the release, version. You said it's fixed now, I am guessing I just need to pull from git?

When it give me the error the page breaks and does not go to database setup page.
I can get to the token. Then I put the token in it just gives me the errors. 

I have the server and the database running using XAMMP.
Is there a quick way to fix this?

**Comment by ejv2** [comment]
I'll need to publish a new release for you that you can download. I'll sort it out for you when I have a spare sec. Sorry leaving you stuck on the installer :)

**Comment by ChuckinAllen** [comment]
All good, I actually just fixed it somehow chatgpt worked as a bandage for now, until you can get a full fix. Was the quickest way I could find without having to debug and try to code it myself. Anyways this was the fix that worked. 
```
function setupDatabaseServer()
{
    for ($i = 0; $i < count(requiredTables); $i++) {
        if (!tableExists(requiredTables[$i])) {
            createDatabaseTable(requiredTables[$i], tableColumns[$i]);
        }
    }

    setupDefaultAccounts();

    // Redirect to the next setup page
    header("Location: next_setup_page.php"); // Replace with your actual next page
    exit();
}
```

This should work for now, but thank you so much for your help I will keep checking for updates.

**Comment by ejv2** [comment]
That code shouldn't work. Does it?

**Comment by ChuckinAllen** [comment]
Somehow it did, here is the whole thing.

```
<?php

const requiredTables = array("users", "siteusers", "accounts", "transactions", "statistics");

const tableColumns = array(
    "`user_id` BIGINT NOT NULL AUTO_INCREMENT , `username` TINYTEXT NOT NULL , `real_name` TEXT NOT NULL , `password_hash` LONGTEXT NOT NULL , `password_hint` TEXT NOT NULL , `email` TEXT NOT NULL , `date_of_registration` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`user_id`)",
    "`user_id` BIGINT NOT NULL AUTO_INCREMENT , `username` TINYTEXT NOT NULL , `real_name` TEXT NOT NULL , `password_hash` LONGTEXT NOT NULL , `password_hint` TEXT NOT NULL , `email` TEXT NOT NULL , `date_of_registration` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `account_enabled` BOOLEAN NOT NULL DEFAULT TRUE, `new_account` BOOLEAN NOT NULL , PRIMARY KEY (`user_id`)",
    "`account_identifier` INT NOT NULL AUTO_INCREMENT , `account_number` INT(11) NOT NULL, `account_name` TEXT NOT NULL , `account_type` ENUM('current','savings','shared','misc') NOT NULL DEFAULT 'current' , `account_balance` DECIMAL(11,2) NOT NULL DEFAULT '0' , `holder_name` TEXT NOT NULL , `associated_online_account_id` INT NOT NULL , `account_disabled` BOOLEAN NOT NULL DEFAULT FALSE , PRIMARY KEY (`account_identifier`)",
    "`transaction_id` BIGINT NOT NULL AUTO_INCREMENT , `transaction_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `origin_account_id` INT NOT NULL , `dest_account_id` INT NOT NULL , `transaction_description` TEXT NOT NULL, `transaction_type` ENUM('transfer','withdrawal','purchase','misc') NOT NULL DEFAULT 'transfer', `transaction_amount` DECIMAL(11,2) NOT NULL , PRIMARY KEY (`transaction_id`)",
    "`stat_name` VARCHAR(255) NOT NULL , `stat_type` INT NOT NULL , `stat_value` INT NOT NULL , `stat_label` TEXT NOT NULL , `stat_category` TEXT NOT NULL , `sys_data` BOOLEAN NOT NULL DEFAULT FALSE , `theme_def` BOOLEAN NOT NULL DEFAULT FALSE , PRIMARY KEY (`stat_name`)"
);

/* Is database fully installed? */
function databaseInstalled()
{
    foreach (requiredTables as $tbl) {
        if (!tableExists($tbl)) {
            return false;
        }
    }
    return true;
}

/* Is database partially installed? */
function someDatabaseInstalled()
{
    foreach (requiredTables as $tbl) {
        if (tableExists($tbl)) {
            return true;
        }
    }
    return false;
}

/* WARNING: dangerous function ahead! Make sure that you have prompted the user before use! */
function resetDatabase()
{
    foreach (requiredTables as $tbl) {
        if (tableExists($tbl)) {
            dropTable($tbl);
        }
    }
}

function dropTable($tbl)
{
    $sql = "DROP TABLE `" . $tbl . "`;";
    $conn = connectToDatabase();

    if ($conn) {
        mysqli_query($conn, $sql);
        mysqli_close($conn);
    }
}

function tableExists($tbl)
{
    $sql = "SELECT * FROM `" . $tbl . "` LIMIT 1;";

    try {
        $conn = connectToDatabase();
        if (!$conn) {
            throw new Exception("Database connection failed.");
        }
        $resp = mysqli_query($conn, $sql);
        mysqli_close($conn);
        return $resp !== false;
    } catch (Exception $e) {
        error_log("Error checking table existence: " . $e->getMessage());
        return false;
    }
}

function setupDatabaseServer()
{
    for ($i = 0; $i < count(requiredTables); $i++) {
        if (!tableExists(requiredTables[$i])) {
            createDatabaseTable(requiredTables[$i], tableColumns[$i]);
        }
    }

    setupDefaultAccounts();

    // Redirect to the next setup page
    header("Location: next_setup_page.php"); // Replace with your actual next page
    exit();
}

function createDatabaseTable($tableName, $cols)
{
    $sql = "CREATE TABLE `" . $tableName . "` (" . $cols . ")";

    $connection = connectToDatabase();

    if ($connection) {
        mysqli_query($connection, $sql);
        mysqli_close($connection);
    }
}

function setupDefaultAccounts()
{
    $configuration = parse_ini_file("../../Config.ini");

    $hostname = $configuration["server_hostname"];
    $dbname = $configuration["database_name"];
    $uname = $configuration["username"];
    $pw = $configuration["password"];

    $sql = new mysqli($hostname, $uname, $pw, $dbname);

    if ($sql->connect_error) {
        error_log("Connection failed: " . $sql->connect_error);
        return;
    }

    $passHash = password_hash("hunter2", PASSWORD_DEFAULT);

    $sql->query("INSERT INTO `users` (`username`, `real_name`, `password_hash`, `password_hint`, `email`) VALUES ('edna', 'Edna Gooseberry', '$passHash', 'Hunter2', 'edna.g@aol.com')");

    $sql->query("INSERT INTO `accounts` (`account_identifier`, `account_number`, `account_name`, `account_type`, `account_balance`, `holder_name`, `associated_online_account_id`, `account_disabled`) VALUES
        (1, 909111628, 'Checking Account', 'current', '1200.00', 'Edna Gooseberry', 1, 0),
        (2, 285058645, 'Savings Account', 'savings', '5420.00', 'Edna Gooseberry', 1, 0),
        (3, 786878148, 'War bond', 'misc', '3600.00', 'Edna Gooseberry', 1, 0),
        (4, 869033308, 'Money Market', 'misc', '1500250.42', 'Edna Gooseberry', 1, 0);
    ");

    $sql->close();
}

function connectToDatabase()
{
    $configuration = parse_ini_file("../../Config.ini");

    $hostname = $configuration["server_hostname"];
    $dbname = $configuration["database_name"];
    $uname = $configuration["username"];
    $pw = $configuration["password"];

    $conn = mysqli_connect($hostname, $uname, $pw, $dbname);

    if (!$conn) {
        error_log("Connection failed: " . mysqli_connect_error());
    }

    return $conn;
}

function safeInsertUser($username, $password_hash, $password_hint, $email, $userid, $realName = "user")
{
    $configuration = parse_ini_file("../../Config.ini");

    $hostname = $configuration["server_hostname"];
    $dbname = $configuration["database_name"];
    $uname = $configuration["username"];
    $pw = $configuration["password"];

    $new = 1;

    $sql = new mysqli($hostname, $uname, $pw, $dbname);

    if ($sql->connect_error) {
        error_log("Connection failed: " . $sql->connect_error);
        return;
    }

    $statement = $sql->prepare("INSERT INTO `siteusers` (`username`, `email`, `password_hash`, `password_hint`, `new_account`, `user_id`, `real_name`) VALUES (?, ?, ?, ?, ?, ?, ?)");

    $username = sanitizeUserCredentials($username, $sql);
    $email = sanitizeUserCredentials($email, $sql);
    $password_hint = sanitizeUserCredentials($password_hint, $sql);

    $statement->bind_param("ssssiis", $username, $email, $password_hash, $password_hint, $new, $userid, $realName);
    $statement->execute();

    $statement->close();
    $sql->close();
}

function sanitizeUserCredentials($value, $sql)
{
    $safeValue = htmlentities($value);
    $safeValue = $sql->escape_string($value);

    return $safeValue;
}

function handleDBVerification()
{
    try {
        $conn = connectToDatabase();
        if ($conn === false) {
            throw new Exception("Database connection failed.");
        }
        return databaseInstalled();
    } catch (Exception $e) {
        error_log("Database verification failed: " . $e->getMessage());
        return false;
    }
}
```

**Comment by ejv2** [comment]
Well, it accidentally fixed the bug by changing something unrelated.

I'll close this issue because we found the issue. If you find any more problems, please open a new one.
