### ISSUE TITLE
DSJAS freaks out when on XAMPP

### ISSUE THREAD

**Issue by WalkTheEarth** [DSJAS/DSJAS#92]
I got this error when using XAMPP (MySQL and Apache started)
```

Warning: require(C:/xampp/htdocs/include//install/Utils.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\banking\include\Bootstrap.php on line 30

Fatal error: Uncaught Error: Failed opening required 'C:/xampp/htdocs/include//install/Utils.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\banking\include\Bootstrap.php:30 Stack trace: #0 C:\xampp\htdocs\banking\Index.php(19): require() #1 {main} thrown in C:\xampp\htdocs\banking\include\Bootstrap.php on line 30
```

**Comment by WalkTheEarth** [comment]
not under xampp
```

Warning: require(C:\Users\Jakub\Downloads\php/include//install/Utils.php): Failed to open stream: No such file or directory in C:\Users\Jakub\Downloads\php\semicolon3\include\Bootstrap.php on line 30

Fatal error: Uncaught Error: Failed opening required 'C:\Users\Jakub\Downloads\php/include//install/Utils.php' (include_path='.;C:\php\pear') in C:\Users\Jakub\Downloads\php\semicolon3\include\Bootstrap.php:30 Stack trace: #0 C:\Users\Jakub\Downloads\php\semicolon3\Index.php(19): require() #1 {main} thrown in C:\Users\Jakub\Downloads\php\semicolon3\include\Bootstrap.php on line 30
```

**Comment by ejv2** [comment]
Hello. What version of php is generating this error? If you try opening this file using the run dialog (press Win+R) does a file open or does the file indeed not exist?

**Comment by WalkTheEarth** [comment]
they all exist. bootstrap, utils, etc

**Comment by WalkTheEarth** [comment]
and mamp works.. but it complains due to " Minimum PHP Requirements Not Met DSJAS requires that PHP has the following optional modules enabled:

    mysqli - for database connections
    exif - for upload handling
    curl - for theme archive downloads
    intl - for currency formatting
    zip - for theme archive unpacking

Please enable all of these modules and try again. Remember to restart your webserver after editing php.ini. "

**Comment by WalkTheEarth** [comment]
hello?

**Comment by ejv2** [comment]
Not sure what's up with XAMPP - sounds like a configuration issue. On MAMP, everything should work once you enable the required modules. See [here](https://github.com/DSJAS/DSJAS/issues/80#issuecomment-1741899806) for a thread about doing this.
